name: dang
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.5.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h91455d4_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=h85f69ea_0
  - brotli-python=1.1.0=py38hd3f51b4_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cpython=3.8.20=py38hd8ed1ab_2
  - debugpy=1.8.5=py38h2698bfa_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freexl=2.0.0=hf297d47_2
  - gdal=3.9.2=py38h94e6548_0
  - geos=3.13.0=h5a68840_0
  - geotiff=1.7.4=h887f4e7_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.12.2=pyh08f2357_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38haa244fe_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - krb5=1.21.3=hdf4eb48_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.7.7=h88ece9c_0
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal-core=3.9.2=h042995d_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - librttopo=1.1.0=hd4c2148_17
  - libsodium=1.0.18=h8d14728_1
  - libspatialite=5.1.0=h939089a_12
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=hdefb170_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.2=hfa2b4ca_3
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - markupsafe=2.1.5=py38h91455d4_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - minizip=4.0.10=h9fa1bad_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.2.2=h57928b3_16
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.24.4=py38h1d91fd2_0
  - openssl=3.5.4=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - proj=9.5.1=h4f671f6_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38h4cb3324_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.20=h8205438_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywinpty=2.0.13=py38hd3f51b4_0
  - pyzmq=26.2.0=py38h3c56b06_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py38h2e0ef18_0
  - send2trash=1.8.3=pyh5737063_0
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.6=pyhd8ed1ab_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.13.0=h18a62a1_3
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tornado=6.4.1=py38h4cb3324_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=haa95532_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.8=h5a68840_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=py38haa95532_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - winpty=0.4.3=4
  - xerces-c=3.2.5=he0c23c2_2
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=he1f189c_4
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.19.0=py38h91455d4_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - addict==2.4.0
      - affine==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.2
      - cycler==0.12.1
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - filelock==3.14.0
      - fonttools==4.57.0
      - ftfy==6.2.3
      - imageio==2.35.1
      - jmespath==0.10.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mat4py==0.6.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.4
      - mmpretrain==1.2.0
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - modelindex==0.0.2
      - narwhals==1.42.1
      - networkx==3.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - plotly==6.3.1
      - prettytable==3.11.0
      - pycocotools==2.0.7
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pywin32==311
      - pyyaml==6.0.3
      - rasterio==1.3.11
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - scikit-image==0.21.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - snuggs==1.4.7
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tifffile==2023.7.10
      - tomli==2.3.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - yapf==0.43.0
      - zipp==3.20.2
prefix: C:\Users\CuongHM\anaconda3\envs\dang
