name: dang
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blosc=1.21.6
  - boost-cpp=1.82.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cfitsio=3.470
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.1.1
  - cpython=3.8.20
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.1
  - fiona=1.9.5
  - folium=0.18.0
  - fontconfig=2.14.1
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=1.0.6
  - gdal=3.6.2
  - geos=3.8.0
  - geotiff=1.7.0
  - glib=2.84.2
  - glib-tools=2.84.2
  - h11=0.14.0
  - h2=4.1.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icc_rt=2022.1.0
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.2.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9f
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kealib=1.5.0
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libarchive=3.6.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.17
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgdal=3.6.2
  - libglib=2.84.2
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.8.1
  - libpng=1.6.50
  - libpq=12.15
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.13
  - libxml2=2.10.4
  - libzip=1.8.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.5
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - minizip=4.0.10
  - mistune=3.0.2
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openssl=3.5.4
  - overrides=7.7.0
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.46.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pooch=1.8.2
  - poppler=22.12.0
  - poppler-data=0.4.12
  - proj=6.2.1
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pyparsing=3.1.4
  - pyproj=2.6.1.post1
  - pysocks=1.7.1
  - python=3.8.20
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.8
  - pywinpty=2.0.13
  - pyzmq=26.2.0
  - qhull=2020.2
  - referencing=0.35.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - rtree=1.0.1
  - scikit-learn=1.3.2
  - send2trash=1.8.3
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.6
  - sqlite=3.50.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tinycss2=1.4.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - affine==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - crcmod==1.7
      - cryptography==46.0.2
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - filelock==3.14.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - geopandas==0.12.2
      - huggingface-hub==0.35.3
      - imageio==2.35.1
      - jmespath==0.10.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mat4py==0.6.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.4
      - mmpretrain==1.2.0
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - modelindex==0.0.2
      - munch==4.0.0
      - narwhals==1.42.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pillow==10.4.0
      - plotly==6.3.1
      - pretrainedmodels==0.7.4
      - prettytable==3.11.0
      - pycocotools==2.0.7
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pywin32==311
      - pyyaml==6.0.3
      - rasterio==1.3.11
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.3.3
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - snuggs==1.4.7
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tifffile==2023.7.10
      - timm==0.9.2
      - tomli==2.3.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - yapf==0.43.0
      - zipp==3.20.2
prefix: C:\Users\CuongHM\anaconda3\envs\dang
